services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
  php:
    build:
      context: .
      dockerfile: ./conf/php/PHP.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/php-fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./app:/app
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'development'
      MYSQL_USER: 'development'
      MYSQL_PASSWORD: 'development'
      MYSQL_DATABASE: 'development'
    volumes:
      - ./app/lib/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: 'development'
      PMA_HOST: 'database'
      PMA_USER: 'development'
      PMA_PASSWORD: 'development'
      APACHE_PORT: 8080
# redis:
#   image: redis
#   volumes:
#     - ./app/redis/redis.conf:/usr/local/etc/redis/redis.conf
#   command: redis-server /usr/local/etc/redis/redis.conf